# Generated by Django 4.0.4 on 2022-04-18 01:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_book_delete_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='color',
            field=models.CharField(blank=True, default=True, max_length=32),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.FloatField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='book',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
